---
title: "Homework_09"
author: "clbenning"
date: "2025-03-26"
output: html_document
---

# Load necessary packages 
```{r}
library(upscaler)
library(pracma)
library(dplyr)
library(readr)
library(stringr)
```

# Question 2: Set working directory and extract subfolders

```{r}
directory <- ("C:/Users/cbennin1/OneDrive - University of Vermont/Documents/BIOL6100/BenningBio6100/Homework_09_files/NEON_count-landbird")
subfolders <- list.files(directory)
subfolders
```

## Create For Loops to extract all the "count data" only
```{r}
count_data <- c() # Create a vector to store the data in 

for (i in 1:10) {
  setwd(paste0("C:/Users/cbennin1/OneDrive - University of Vermont/Documents/BIOL6100/BenningBio6100/Homework_09_files/NEON_count-landbird","/", subfolders[i]))
  count_data[i] <- list.files(pattern = "countdata")
}

count_data
```

# Question 3: Clean up the data 

## Remove empty or missing cases 


```{r}

years <- (2013:2025)

for (i in 1:10) {
  print(subfolders[i])
  setwd(paste0("C:/Users/cbennin1/OneDrive - University of Vermont/Documents/BIOL6100/BenningBio6100/Homework_09_files/NEON_count-landbird","/", subfolders[i]))
  raw_data <- read.csv(count_data[i], na.strings = c("","NA")) # Extract raw data
  clean_data <- raw_data[complete.cases(raw_data["scientificName"]), ] # Clean the data 
    write.csv(clean_data,paste0("clean_data", years[i], ".csv"))
}
```


```{r}
clean_data <- list()

for(i in 1:10) {
  setwd(paste0("C:/Users/cbennin1/OneDrive - University of Vermont/Documents/BIOL6100/BenningBio6100/Homework_09_files/NEON_count-landbird","/", subfolders[i]))
  raw_data <- read.csv(count_data[i], na.strings = c("","NA")) 
  clean_count_data <- raw_data[complete.cases(raw_data["scientificName"]), ]
  clean_data[[i]] <- clean_count_data
}

dat <- do.call("rbind", clean_data)
head(dat)

```


```{r}
library(Rmisc)
years <- str_sub(dat$startDate, 1, 4)
dat <- cbind(dat, years)


abundance_dat <- summarySE(data = dat, measurevar = "scientificName", groupvars = "years", na.rm = FALSE)

abundance_dat <- abundance_dat[, 1:2]

richness_dat <- summarySE(data = dat, measurevar = "vernacularName", groupvars = c("years", "scientificName"), na.rm = FALSE)

richness_dat <- richness_dat[,1:3]

richness_dat %>% count(richness_dat$years)

richness <- c(40, 38, 33, 35, 43, 45, 48, 37, 40)

sum_dat <- cbind(abundance_dat, richness)

print(sum_dat)

```


